<a href="https://colab.research.google.com/github/zsabro/Batch04_to_35/blob/main/IOT055274_Zeeshan_Assignment02_ip.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [114]:
def function3():
    #extract those numbers from given array. those are must exist in 5,7 Table
    #example [35,70,105,..]
    a = np.arange(1, 100*10+1).reshape((100,10))
    x = np.where(a%5 == 1) and np.where(a%7 == 1) #wrtie your code here
    return x
    """
    Expected Output:
     [35,  70, 105, 140, 175, 210, 245, 280, 315, 350, 385, 420, 455,
       490, 525, 560, 595, 630, 665, 700, 735, 770, 805, 840, 875, 910,
       945, 980] 
    """
function3() 

(array([ 0,  0,  1,  2,  2,  3,  4,  4,  5,  6,  7,  7,  8,  9,  9, 10, 11,
        11, 12, 13, 14, 14, 15, 16, 16, 17, 18, 18, 19, 20, 21, 21, 22, 23,
        23, 24, 25, 25, 26, 27, 28, 28, 29, 30, 30, 31, 32, 32, 33, 34, 35,
        35, 36, 37, 37, 38, 39, 39, 40, 41, 42, 42, 43, 44, 44, 45, 46, 46,
        47, 48, 49, 49, 50, 51, 51, 52, 53, 53, 54, 55, 56, 56, 57, 58, 58,
        59, 60, 60, 61, 62, 63, 63, 64, 65, 65, 66, 67, 67, 68, 69, 70, 70,
        71, 72, 72, 73, 74, 74, 75, 76, 77, 77, 78, 79, 79, 80, 81, 81, 82,
        83, 84, 84, 85, 86, 86, 87, 88, 88, 89, 90, 91, 91, 92, 93, 93, 94,
        95, 95, 96, 97, 98, 98, 99]),
 array([0, 7, 4, 1, 8, 5, 2, 9, 6, 3, 0, 7, 4, 1, 8, 5, 2, 9, 6, 3, 0, 7,
        4, 1, 8, 5, 2, 9, 6, 3, 0, 7, 4, 1, 8, 5, 2, 9, 6, 3, 0, 7, 4, 1,
        8, 5, 2, 9, 6, 3, 0, 7, 4, 1, 8, 5, 2, 9, 6, 3, 0, 7, 4, 1, 8, 5,
        2, 9, 6, 3, 0, 7, 4, 1, 8, 5, 2, 9, 6, 3, 0, 7, 4, 1, 8, 5, 2, 9,
        6, 3, 0, 7, 4, 1, 8, 5, 2, 9, 6, 3, 0, 7, 4, 1, 8,

In [ ]:
def function4():
    #Swap columns 1 and 2 in the array arr.
   
    arr = np.arange(9).reshape(3,3)
    print(arr)
    return arr.swapaxes(0, 1) #wrtie your code here
    """
    Expected Output:
          array([[1, 0, 2],
                [4, 3, 5],
                [7, 6, 8]])
    """ 
function4()

In [ ]:
def function5():
  #Create a null vector of size 20 with 4 rows and 5 columns with numpy function
  z = np.zeros(20).reshape(4, 5) #wrtie your code here
  return z
  """
    Expected Output:
          array([[0, 0, 0, 0, 0],
                [0, 0, 0, 0, 0],
                [0, 0, 0, 0, 0],
                [0, 0, 0, 0, 0]])
    """
function5()

In [ ]:
#task6
def function6():
    # Create a null vector of size 10 but the fifth and eighth value which is 10,20 respectively
   
    arr = np.zeros(10) #wrtie your code here
    #arr = np.insert((5,(10))
    return arr
function6()

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
#task7
def function7():
    #  Create an array of zeros with the same shape and type as X. Dont use reshape method
    x = np.arange(4, dtype=np.int64)
    print(x)
    arr = x - x # np.zeros(4) #write your code here
    return arr
    """
    Expected Output:
          array([0, 0, 0, 0], dtype=int64)
    """ 
function7()

In [ ]:
#task8
def function8():
    # Create a new array of 2x5 uints, filled with 6.
    x = np.ones(dtype=np.uint32, shape=(2,5))
    arr = x * 6 #write your code here
    return arr
    
    """
     Expected Output:
              array([[6, 6, 6, 6, 6],
                     [6, 6, 6, 6, 6]], dtype=uint32)
    """
function8()

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]], dtype=uint32)

In [ ]:
#task9
def function9():
    # Create an array of 2, 4, 6, 8, ..., 100.
    a = np.array(100**2) # write your code here
    return a

    """
     Expected Output:
              array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
                    28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
                    54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
                    80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])
    """
function9

<function __main__.function9>

In [ ]:
#task10
def function10():
    # Subtract the 1d array brr from the 2d array arr, such that each item of brr subtracts from respective row of arr.
    
    arr = np.array([[3,3,3],[4,4,4],[5,5,5]])
    brr = np.array([1,2,3])
    subt = arr - brr # write your code here 
  
    return subt

    """
     Expected Output:
               array([[2 2 2]
                      [2 2 2]
                      [2 2 2]])
    """
function10()

array([[2, 1, 0],
       [3, 2, 1],
       [4, 3, 2]])

In [ ]:
#task11
def function11():
    # Replace all odd numbers in arr with -1 without changing arr.
    
    arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
    ans = np.where(arr/2, -1) #= #write your code here
    return ans 
    #print(ans)

    """
     Expected Output:
              array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])
    """
function11 

<function __main__.function11>

In [ ]:
#task12
def function12():
    # Create the following pattern without hardcoding. Use only numpy functions and the below input array arr.
    # HINT: use stacking concept
    
    arr = np.array([1,2,3])
    ans = np.concatenate([arr, arr]) #write your code here 
  
    return ans

    """
     Expected Output:
              array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
    """
function12()

array([1, 2, 3, 1, 2, 3])

In [ ]:
#task13
def function13():
    # Set a condition which gets all items between 5 and 10 from arr.
    
    
    arr = np.array([2, 6, 1, 9, 10, 3, 27])
    arr>=5 and arr<=10
    x = arr.all()
    ans = x
    # ans = arr # np.where(arr>=5 and arr<=10) #write your code here 
    return ans

    """
     Expected Output:
              array([6, 9])
    """
function13()

ValueError: ignored

In [ ]:
import numpy as np

#task14
def function14():
    # Create an 8X3 integer array from a range between 10 to 34 such that the difference between each element is 1 and then Split the array into four equal-sized sub-arrays.
    # Hint use split method
    arr = np.arange(10, 34, 1).reshape(4, 3, 2) #write reshape code
    print(arr)
    ans = np.split(arr, 4, 3) #write your code here 
    return ans
"""
     Expected Output:
       [array([[10, 11, 12],[13, 14, 15]]), 
        array([[16, 17, 18],[19, 20, 21]]), 
        array([[22, 23, 24],[25, 26, 27]]), 
        array([[28, 29, 30],[31, 32, 33]])]
""" 
function14()

In [ ]:
import numpy as np 
#task15
def function15():
    #Sort following NumPy array by the second column
    
    
    arr = np.array([[ 8,  2, -2],[-4,  1,  7],[ 6,  3,  9]])
    ans = np.sort(arr, -1) #write your code here 
  
    return ans
    
    """
     Expected Output:
           array([[-4,  1,  7],
                   [ 8,  2, -2],
                   [ 6,  3,  9]])
    """ 

function15()

In [ ]:
#task16
def function16():
    #Write a NumPy program to join a sequence of arrays along depth.
    
    
    x = np.array([[1], [2], [3]])
    y = np.array([[2], [3], [4]])
    print(x)
    print(y)
    ans = np.concatenate((x, y), axis = 1) #write your code here 
    return ans
    """
     Expected Output:
                [[[1 2]]

                 [[2 3]]

                 [[3 4]]]
    """
function16()

In [ ]:
#Task17
def function17():
    # replace numbers with "YES" if it divided by 3 and 5
    # otherwise it will be replaced with "NO"
    # Hint: np.where
    arr = np.arange(1,10*10+1).reshape((10,10))
    x = np.where(arr %3 == 1, "yes", "no")
    return x
    # return x           # Write Your Code HERE

#Excpected Out
"""
array([['NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO'],
       ['NO', 'NO', 'NO', 'NO', 'YES', 'NO', 'NO', 'NO', 'NO', 'NO'],
       ['NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'YES'],
       ['NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO'],
       ['NO', 'NO', 'NO', 'NO', 'YES', 'NO', 'NO', 'NO', 'NO', 'NO'],
       ['NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'YES'],
       ['NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO'],
       ['NO', 'NO', 'NO', 'NO', 'YES', 'NO', 'NO', 'NO', 'NO', 'NO'],
       ['NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'YES'],
       ['NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO', 'NO']],
      dtype='<U3')
"""
function17()

array([['yes', 'no', 'no', 'yes', 'no', 'no', 'yes', 'no', 'no', 'yes'],
       ['no', 'no', 'yes', 'no', 'no', 'yes', 'no', 'no', 'yes', 'no'],
       ['no', 'yes', 'no', 'no', 'yes', 'no', 'no', 'yes', 'no', 'no'],
       ['yes', 'no', 'no', 'yes', 'no', 'no', 'yes', 'no', 'no', 'yes'],
       ['no', 'no', 'yes', 'no', 'no', 'yes', 'no', 'no', 'yes', 'no'],
       ['no', 'yes', 'no', 'no', 'yes', 'no', 'no', 'yes', 'no', 'no'],
       ['yes', 'no', 'no', 'yes', 'no', 'no', 'yes', 'no', 'no', 'yes'],
       ['no', 'no', 'yes', 'no', 'no', 'yes', 'no', 'no', 'yes', 'no'],
       ['no', 'yes', 'no', 'no', 'yes', 'no', 'no', 'yes', 'no', 'no'],
       ['yes', 'no', 'no', 'yes', 'no', 'no', 'yes', 'no', 'no', 'yes']],
      dtype='<U3')

In [ ]:
# Task19
def function19():
    #Create variable "X" from 1,25 (both are included) range values
    #Convert "X" variable dimension into 5 rows and 5 columns
    #Create one more variable "W" copy of "X" 
    #Swap "W" row and column axis (like transpose)
    # then create variable "b" with value equal to 5
    # Now return output as "(X*W)+b:

    X =   np.arange(1, 26).reshape(5, 5)# Write your code here
    W =   X.T # Write your code here 
    b =   5 # Write your code here
    output = (X*W)+b   # Write your code here
    return output
    #expected output
    """
    array([[  6,  17,  38,  69, 110],
       [ 17,  54, 101, 158, 225],
       [ 38, 101, 174, 257, 350],
       [ 69, 158, 257, 366, 485],
       [110, 225, 350, 485, 630]])
    """
function19()

In [ ]:
#Task20
def function20(a):
    #apply fuction "abc" on each value of Array "X"
    #x = np.arange(1,11)
    #def abc(x):
    return x*2+3-2

x = np.arange(1,11)
print(function20(x))
    #return x #Write your Code here
#Expected Output: array([ 3,  5,  7,  9, 11, 13, 15, 17, 19, 21])


[ 3  5  7  9 11 13 15 17 19 21]
